# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Connor's Website  
email: cm1911@s.maynard.k12.ma.us
description: > # this means to ignore newlines until "baseurl:"
This is my new website! This is where I will be doing a majority of my work. 
baseurl: "/jekyll-simple" # the subpath of your site, e.g. /blog
url: http://connorm.me/org-protocol-jekyll
twitter_username: None 
github_username:  cmortis 

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
